### ISSUE TITLE
Request mis-signed: Invalid or Missing Signature in accountInfo.php

### ISSUE THREAD

**Issue by Caster** [BenExile/Dropbox#23]
#### Description

Hi,

I am planning on using your SDK, which by the way looks really good. After downloading it, the first thing I wanted to do was run some examples. After having set my app key and secret I ran accountInfo.php, just to check. To my surprise, I got a warning and an error. Since I have no clue what causes this, I was wondering if you can help me out here. I sincerely hope this is not something stupid... To try and solve the first warning, I have tried to switch off safe_mode and set open_basedir to the empty string, but that seemed not to have any effect. Also, of course, I have checked and double-checked my app key and secret.

Thanks in advance!
Thom
#### PHP output:

_(slightly modified: stripped paths and app key/secret)_

**Warning:** curl_setopt_array() [function.curl-setopt-array]: CURLOPT_FOLLOWLOCATION cannot be activated when safe_mode is enabled or an open_basedir is set in **/.../Dropbox/OAuth/Consumer/Curl.php** on line **89**

**Fatal error:** Uncaught exception 'Dropbox\Exception' with message 'OAuthError in API v1+. Request mis-signed: Invalid or Missing Signature (Status Code: 401)' in /.../Dropbox/OAuth/Consumer/Curl.php:103
Stack trace
#0 /.../Dropbox/OAuth/Consumer/ConsumerAbstract.php(68): Dropbox\OAuth\Consumer\Curl->fetch('POST', 'https://api.dro...', '')
#1 /.../Dropbox/OAuth/Consumer/ConsumerAbstract.php(50): Dropbox\OAuth\Consumer\ConsumerAbstract->getRequestToken()
#2 /.../Dropbox/OAuth/Consumer/Curl.php(47): Dropbox\OAuth\Consumer\ConsumerAbstract->authenticate()
#3 /.../examples/bootstrap.php(42): Dropbox\OAuth\Consumer\Curl->__construct('_my app key_', '_my app secret_', Object(Dropbox\OAuth\Storage\Session), 'http://www....')
#4 in **/.../Dropbox/OAuth/Consumer/Curl.php** on line **103**

**Comment by BenExile** [comment]
Hi @Caster 

The first issue is using `CURLOPT_FOLLOWLOCATION` with safe_mode or an open_basedir set (please advise which one for future reference). If these aren't a requirement then you can disable them, otherwise you will need to disable [`CURLOPT_FOLLOWLOCATION`](https://github.com/BenTheDesigner/Dropbox/blob/master/Dropbox/OAuth/Consumer/Curl.php#L26) by setting it to false.

This is a preventative measure put in place in case Dropbox ever send 'Location: ' headers back with the API responses. I don't think they currently do and will get in touch with their team to see if this can be removed altogether.

If you could resolve this issue and advise whether you still have the invalid signature that would be great.

**Comment by Caster** [comment]
Thanks a lot for the hint @BenTheDesigner.

It appeared `safe_mode` was off and hence could not be the issue, but I had an `open_basedir` set. Since I did not want to change this, I set `CURLOPT_FOLLOWLOCATION` to false as you indicated, which resolved the issue.

Cheers!
