### ISSUE TITLE
add input box to putfile

### ISSUE THREAD

**Issue by simwatts2** [BenExile/Dropbox#42]
How can I go about implementing this.

$FilePath = "c:\user\test\koala.jpg";

 $put = $dropbox->putFile($FilePath);

or

 $put = $dropbox->putFile("c:\user\test\koala.jpg");

This works great.

How can I add a simple input box to get local file, and pass this to putfile.

Obviously cant use full path to security restrictions.

**Comment by BenExile** [comment]
Hi,

You can achieve this in the same way as uploading any file. You'll need to create a form element of type 'file' and ensure you set your enctype to multipart/form-data. Once the form is posted, you'll be able to access it via it's temporary location detailed in the $_FILES superglobal i.e. $_FILES['element_name']['tmp_name'], and use this path in your API call.

Hope this helps.

**Comment by simwatts2** [comment]
Hi Ben, thanks for reply. Will this upload, or post, to my server first. I am trying to avoid this if I can. I mean if a user uploaded some media. Does it upload the whole media to my server first as a tmp file.

**Comment by BenExile** [comment]
Hi,

Your server is the intermediary step between the browser and Dropbox. Whether you use a simple form or an upload handler (such as Plupload), you'll need to post the file data to your server in order to upload it via the web API.

Off the top of my head, and having consulted someone else, PHP will wait until the file is received before you can access it. There's probably a way to get PHP to handle partial data as it is received, but by the time you've worked that out (and dealt with the complications you'll encounter) you could have launched your app. KISS principle here :)
