### ISSUE TITLE
Chunked upload does not upload on windows, but works fine on linux

### ISSUE THREAD

**Issue by cha0ss** [BenExile/Dropbox#47]
Hi.

First i tested everything on linux , and it works fine .... but then i switched to windows , and encountered a problem with chunkedUpload  function , though putFile works fine.

First error was  'Too long upload' , but as i understood if file is smaller than chunk , then it fails. Am i correct ? 

But after supplying larger file i got another error (  Fatal error: Maximum execution time of 30 seconds exceeded in F:\xampp\htdocs\test\Dropbox\OAuth\Consumer\Curl.php on line 93 )

---

string 'HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Server: nginx/1.2.3
Date: Tue, 02 Oct 2012 23:53:47 GMT
Content-Type: application/x-www-form-urlencoded
Transfer-Encoding: chunked
Connection: keep-alive
access-control-expose-headers: X-Dropbox-Metadata
pragma: no-cache
cache-control: no-cache
x-frame-options: SAMEORIGIN
access-control-allow-origin: *

oauth_token_secret=5ofp9wi15ybhkmk&oauth_token=q7j73ftoig9oa5d' (length=420)

resource(11, stream)
string 'HTTP/1.1 100 Continue

HTTP/1.1 500 Internal Server Error
Server: nginx/1.2.3
Date: Tue, 02 Oct 2012 23:54:04 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
pragma: no-cache
cache-control: no-cache

(length=256) ,
resource(15, stream)

---

Would be great if u can suggest something... Because i am not sure how to debug for example , the progress of file upload , exactly those chunks .  And why it takes more than 30 seconds, timeouts , though the same file\function works fine  on linux .... I am confused.

Just tried to set max_execution_time to 360 , basically 5 minutes and still get ' Dropbox\Exception: Internal Server Error (Status Code: 500) in F:\xampp\htdocs\test\Dropbox\OAuth\Consumer\Curl.php on line 106 '

HTTP/1.1 500 Internal Server Error
Server: nginx/1.2.3
Date: Wed, 03 Oct 2012 00:41:10 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
pragma: no-cache
cache-control: no-cache

{"error": "Internal Server Error"}' (length=290)

**Comment by BenExile** [comment]
Hi,

I've not experienced this problem but will try and help you based on the limited information I have about the issue.

##### Execution time

Execution time will vary from system to system. The example I've provided gets round this by calling `set_time_limit(0)`, which allows the script to run indefinitely. I've uploaded files of around 500MB in size under Windows - can you advise if you're using the example code or something you've coded yourself?

I have just tested uploading a 426MB file under Windows 7 (x64) with no issues other than it taking a long time due to the upload speed I have on my residential connection. Response:

array(3) { ["code"]=> string(3) "200" ["body"]=> object(stdClass)#8 (12) { ["revision"]=> int(49) ["rev"]=> string(10) "3105b7d537" ["thumb_exists"]=> bool(false) ["bytes"]=> int(446684064) ["modified"]=> string(31) "Wed, 03 Oct 2012 11:58:20 +0000" ["client_mtime"]=> string(31) "Wed, 03 Oct 2012 11:58:20 +0000" ["path"]=> string(25) "/dummy.bin" ["is_dir"]=> bool(false) ["icon"]=> string(15) "page_white_gear" ["root"]=> string(10) "app_folder" ["mime_type"]=> string(27) "application/octet-stream" ["size"]=> string(6) "426 MB" } ["headers"]=> array(9) { ["server"]=> string(11) "nginx/1.2.3" ["date"]=> string(29) "Wed, 03 Oct 2012 11:58:25 GMT" ["content-type"]=> string(15) "text/javascript" ["transfer-encoding"]=> string(7) "chunked" ["connection"]=> string(10) "keep-alive" ["access-control-allow-origin"]=> string(1) "*" ["access-control-expose-headers"]=> string(18) "X-Dropbox-Metadata" ["pragma"]=> string(8) "no-cache" ["cache-control"]=> string(8) "no-cache" } } 

##### Chunked upload with small file

To clarify, `chunkedUpload()` should not fail if the file is smaller than the chunk size. What made you suggest this?

##### 5XX errors

Errors with status codes 5XX are server errors as described [here](https://www.dropbox.com/developers/reference/api#error-handling). You'd have to contact Dropbox, with the details of the failed API call to see if they can help you resolve it.

**Comment by BenExile** [comment]
Closed due to inactivity
