### ISSUE TITLE
Object-oriented Autoload Function

### ISSUE THREAD

**Issue by numbleroot** [BenExile/Dropbox#50]
Hey,
is there a way to implement this special autoload function to include the unknown new class instances in a way, that it is possible to use the existing code in a self-written class?
I'd like to put all important things from bootstrap.php into the __construct() function of a class that needs connection to my Dropbox. The existing instanciating-syntax ("new \Dropbox.....") should work in this __construct() function afterwards.

Is that possible and if so, how?

Great project, thanks a lot for putting it on GitHub!

**Comment by BenExile** [comment]
Hi,

This library conforms to PSR-0 and so will be compatible with any PSR-0 autoloader.

If you don't currently use an autoloader it may be worth looking at implementing one for the project rather than for this library specifically. If this is not an option you can copy/paste the function from bootstrap.php and adjust the paths.

Hope this helps

**Comment by numbleroot** [comment]
Okay, great, thanks!
