### ISSUE TITLE
Session caches are shared between instances

### ISSUE THREAD

**Issue by Bugster** [BenExile/Dropbox#68]
When a storage is created with an id, subsequent storage instances will use the same cache, meaning they access files from the first user's dropbox account, instead of the one specified.

This is only a problem if multiple users are accessed in 1 session, e.g.

```
function getFile($userID)
{
    $key = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';
    $encrypter = new \Dropbox\OAuth\Storage\Encrypter($key);

    $storage = new \Dropbox\OAuth\Storage\PDO($encrypter, $userID);

    $OAuth = new \Dropbox\OAuth\Consumer\Curl($key, $secret, $storage, $callback);
    $dropbox = new \Dropbox\API($OAuth);

    return $dropbox->getFile("user1s_file.txt");

}

$file1 = getFile("User1");
$file2 = getFile("User2");

var_dump($file1==$file2); // => bool(true)
```

Both files are referencing the same file, even though $storage and $dropbox are destroyed.
The keys for User1 are stored in the session and are reused for User2, so User2 would seem to be User1.

Some solutions would be to either:
- Cache the tokens in private variables, which would be fine for most things, seeing as reading from the disk/doing a query once per page load is hardly taxing.
- Have an option to disable caching

**Comment by BenExile** [comment]
Hi @Bugster 

Thanks for raising this issue. I hadn't encountered it as until now I've only been testing access to a single Dropbox account at any one time (clearing sessions and tokens stored in the database in between switching accounts).

I have patched the library to allow for multiple users Dropbox account to be accessed by storing tokens in the session by user ID ($_SESSION['dropbox_api']['user_id']) rather than a single user. Forgot to commit some changes first time round - these were added in the second commit.

This update does not allow the same storage object to be used for different user ID's, but I do plan to address this in time. The main problem is that the consumer object that is created performs the token check and redirects if one does not exist. Without changing the way this works we can't switch between user ID's, but this is quite a big change to the core functionality that may affect applications in production.

Hope this helps.
