### ISSUE TITLE
Include error when setting magic_quotes_gpc = Off in php.ini

### ISSUE THREAD

**Issue by hiwatt** [BenExile/Dropbox#75]
Thanks for your wonderful API. It works (almost) perfect:

When I set "magic_quotes_gpc = Off" in php.ini I get the following error:

Warning: require_once(PDO.php) [function.require-once]: failed to open stream: No such file or directory in /path/bootstrap.php on line 26

Fatal error: require_once() [function.require]: Failed opening required 'PDO.php' (include_path='.:/usr/lib/php') in /path/bootstrap.php on line 26

If I delete that line in the ini-file - everything works as expected. I echoed the classes to be loaded to see where it may break, that's the output:

Dropbox/OAuth/Storage/Encrypter
Dropbox/OAuth/Storage/PDO
Dropbox/OAuth/Storage/Session
Dropbox/OAuth/Storage/StorageInterface
PDO

PHP Version is: 5.3.21. Interestingly, it works with the same setting on another server without a problem.

Thanks for your support. David.

**Comment by BenExile** [comment]
Hi @hiwatt 

This sounds like a configuration issue to be honest, especially because it works on another server. Double check your configuration against the working server and see if there are any discrepancies (incorrect include path or similar). If you still have issues after that then please let me know.

**Comment by BenExile** [comment]
Closed due to inactivity
