### ISSUE TITLE
oauth_token parameter not found

### ISSUE THREAD

**Issue by NimbleHost** [BenExile/Dropbox#8]
We're trying to integrate this library into a Slim-based web app, and testing it here:

http://test.nimblehost.com/armadillo/files/armadillo/

To access the current implementation login with user: `guest` and password: `guest` -- then visit:

http://test.nimblehost.com/armadillo/files/armadillo/dropbox

Although you'll be directed to the Dropbox site correctly, when clicking "Allow" and being redirected back to our site, an error will occur stating that the `oauth_token` parameter can't be found. Trying to display `var_dump($_SESSION['dropbox_api']);` also results in an error, so I'm assuming the session variable is not being set correctly. We can, however, directly access the `$_GET` variables `oauth_token` and `uid`.

My guess is that some adjustment needs to be made when using this with a Slim-based app. Might you have any suggestions to that effect, or might this be something that should be handled in the library itself?

**Comment by BenExile** [comment]
Hi @NimbleHost 

Thank you for raising this issue. What you have described suggests that the request token is not being stored in the session, resulting in the `ConsumerAbstract::getAccessToken()` call failing.

I think the place to start would be by running the examples in a standalone environment to establish whether this is a problem with the library or platform, or if it is caused by the integration with Slim framework.

Can you confirm whether you can run the examples successfully?

**Comment by NimbleHost** [comment]
Hi Ben,

The examples do work successfully, when tested in a standalone environment separately from Slim. 

Regarding sessions, I believe Slim also encrypts session data, but does so transparently so that we can use the `$_SESSION` variable just like normal. More info on Slim sessions is here:

http://www.slimframework.com/documentation/stable#slim-sessions

My first thought at this point is to try manually setting the session data that your library is looking for, in the routes we have specified in our Slim app. Or perhaps there's a better alternative?

**Comment by BenExile** [comment]
Hi @NimbleHost 

Without detailed knowledge of the internals of Slim it's going to be difficult for me to provide support. I hate to pass the buck, but as the examples work as expected you may have more luck contacting the author/core contributors of Slim as they may be able to outline any issues/quirks accessing $_SESSION data directly.

I will leave this issue open until you have managed to resolve your problem and assist where possible. This should not be considered a bug with the library itself, though.

**Comment by NimbleHost** [comment]
Hi Ben,

I understand. Although I had already contacted the Slim dev before posting here, actually. ;-)

As I mentioned previously, we can manually set the session data that the library is looking for -- however, I don't know how it should be structured (though I have dug around in the library trying to figure it out). Can you share some info on the structure of the data stored in the `$_SESSION['dropbox_api']` variable that the library is expecting? Is it an array? What kind of variables/objects are stored there?

Best,

Jonathan

**Comment by BenExile** [comment]
Hi Jonathan,

What was the developers response? Maybe @codeguy could jump in on this one if he has time?

If by manually setting the session data you simply mean writing the token directly to the `$_SESSION` superglobal then I'm unsure how this will solve your problem - this is how the storage handler currently works anyway. Have you tried disabling Slim's cookie based session handler and using the default to see if the problem is linked directly to this?

The data stored in `$_SESSION['dropbox_api']` is the optionally encrypted request and access token stdClass objects. The tokens are stored in `$_SESSION['dropbox_api']['request_token']` and `$_SESSION['dropbox_api']['access_token']`. If you choose to use the encrypter then these will be stored as strings (the serialized object, encrypted and base64 encoded), if not, then the token will be stored as an object (and (un)serialized internally by PHP).

Regards,
Ben

**Comment by NimbleHost** [comment]
Appreciate your patience with me, Ben. No doubt I'm going to display some ignorance here, but this is my reasoning:

`$_SESSION['dropbox_api']` isn't getting set when using the library with a Slim app, but is when used in a standalone environment. Hence, there's something about Slim that prevents `$_SESSION['dropbox_api']` from getting set in a way that the library expects. 

However, within our Slim app, I can manually set `$_SESSION['dropbox_api']` using Slim's standard session handler. So, if I set `$_SESSION['dropbox_api']` in our Slim app in the same way that your library is expecting, then your library can (should be able to?) access it "just like normal". Does that makes sense? Or is this too simplistic, perhaps?

You mention "if I choose to use the encrypter" -- I wasn't aware this was something we could opt-out of. But it sounds like we should not be using the encrypter, since Slim already encrypts session data for us. I'll see if I can work out how to do this.

I will contact @codeguy to see if he can chime in here as well.

**Comment by codeguy** [comment]
@NimbleHost I think I may know what is going wrong. I've DM'd you on Twitter. If you are available to Skype on Tuesday morning, I can work with you to fix your session issue.

**Comment by NimbleHost** [comment]
Thanks @codeguy, really appreciate the help. @BenTheDesigner I'll post here again once we've found a solution.

Best,

Jonathan

**Comment by BenExile** [comment]
Hi @NimbleHost 

My library will be able to access any value in the $_SESSION. Hopefully between yourself and @codeguy you'll be able to determine why you're not able to write the token to it successfully. I'm assuming this is something to do with a custom session.save_handler but could be wrong.

The use of encryption in the Dropbox library is optional and can be disabled by passing no arguments when creating the storage object rather than an instance of the Encrypter class. If Slim encrypts sesion data then you do not need to use the Encrypter and it can be disabled like so:

``` php
// Disable token encryption by passing no arguments
$storage = new \Dropbox\OAuth\Storage\Session();
```

If, however, you are not using Slim's built in encryption then you should use the Encrypter. OAuth tokens should be handled with the same care as passwords and never stored in their plain text form.

Regards,
Ben

**Comment by NimbleHost** [comment]
Thanks, Ben. Appreciate the reinforcement.

I talked with @codeguy this morning, and he made some very helpful suggestions. I've made a bit more progress (the application is now getting linked to Dropbox at least) but problems remain. I don't believe, however, that these problems are with the library itself.

If I could offer some constructive feedback here - more detailed documentation on using the library would be of great assistance. The Dropbox API site has no PHP-specific info, and the documentation in this library is...sparse. Thus, the dev (us) is left to figure out how things work, and it's not always clear how the pieces are supposed to fit together.

Just as a basis of comparison, the Slim framework (also open source, also maintained by one guy in his spare time) has great documentation that has allowed us to figure out how things work, without bothering the developer directly (except in rare cases). Similar documentation here would be tremendous.

Thanks for you time and effort. I'm look forward to seeing how this library will improve and grow over time.

Best,

Jonathan

**Comment by BenExile** [comment]
Hi @NimbleHost 

I'm glad you're on the way to getting things sorted. Please feel free to get in touch if you need clarification on anything.

The documentation, examples and unit tests are all being worked. I appreciate the feedback regarding documentation and this has been taken on board.

Regards,
Ben
